max_gas_price_eth_gwei_bridge_action: 100
max_gas_price_eth_gwei_usual_actions: 0.80  # Base

shuffle_keys: true
proxy_mode: no_proxy  # no_proxy, use_proxy

rpc_base: https://base.publicnode.com/

swap_eth_amount: [0.0003, 0.0006]
swap_eth_percent: [15, 35]
bridge_eth_percent: [10, 20]
wrap_eth_percent: [10, 20]

chains: ["base"]

actions_repeat: [4, 10]

prompts:
  - "swap {swap_eth_amount} eth for USDC on base chain"
  - "swap {swap_eth_amount} eth for USDT on base chain"
  - "swap {swap_eth_amount} eth for DAI on base chain"
  - "swap {swap_eth_percent}% eth for USDC on base chain"
  - "swap {swap_eth_percent}% eth for USDT on base chain"
  - "swap {swap_eth_percent}% eth for DAI on base chain"
  - "swap all USDC to ETH on base chain"
  - "swap all USDT to ETH on base chain"
  - "swap all DAI to ETH on base chain"
  - "swap all USDC, USDT, DAI to ETH on base chain"
  - "bridge {bridge_eth_percent}% of eth to optimism chain and {bridge_eth_percent}% to arbitrum chain"
  - "bridge {bridge_eth_percent}% of eth to optimism chain"
  - "bridge {bridge_eth_percent}% of eth to arbitrum chain"
  - "bridge all eth from optimism to base chain"
  - "bridge all eth from arbitrum to base chain"
  - "Wrap {wrap_eth_percent}% eth on base chain"
  - "Unwrap {wrap_eth_percent}% eth on base chain"
  - "Unwrap all eth"


keys_file_path: keys.txt

step_executor:
  rpc_base: ${rpc_base}
  actions_repeat: ${actions_repeat}
  prompts: ${prompts}
  chains: ${chains}

  swap_eth_amount: ${swap_eth_amount}
  swap_eth_percent: ${swap_eth_percent}
  bridge_eth_percent: ${bridge_eth_percent}
  wrap_eth_percent: ${wrap_eth_percent}

  wait_before_after_authorization_sec: [5, 11]
  wait_before_action_sec: [12, 55]
  timeout_between_wallets_src: [340, 840]

base_web3_transaction_executor:
  gas_price_multiplier: 1.15
  balance_check_interval: 30
  transaction_wait_attempts: -1
  transaction_wait_retry_interval: 10

  max_gas_price_eth_gwei_bridge_action: ${max_gas_price_eth_gwei_bridge_action}
  max_gas_price_eth_gwei_usual_actions: ${max_gas_price_eth_gwei_usual_actions}

logs:
  dir_path: logs/
  file_path: ${logs.dir_path}/${now:%Y-%m-%d}.log
  level: INFO
  telegram:
    enabled: False
    token: ""
    chat_id: 0